"""
Iain Muir, iam9ez

"""

import os

if os.environ['USER'] == 'iainmuir':
    API_KEY = os.environ["API_KEY"]
else:
    API_KEY = 'bvgk9c748v6oab530k90'

DOW_JONES = [
    'BA',
    'DOW',
    'AXP',
    'CSCO',
    'JNJ',
    'GS',
    'IBM',
    'JPM',
    'WMT',
    'TRV',
    'HD',
    'NKE',
    'AAPL',
    'MMM',
    'MSFT',
    'PG',
    'CAT',
    'DIS',
    'UNH',
    'V',
    'CRM',
    'VZ',
    'WBA',
    'HON',
    'CVX',
    'MCD',
    'MRK',
    'KO',
    'INTC',
    'AMGN'
]

STATE_CODES = {
    'Washington, D.C.': 'DC', 'Mississippi': 'MS', 'Oklahoma': 'OK',
    'Delaware': 'DE', 'Minnesota': 'MN', 'Illinois': 'IL', 'Arkansas': 'AR',
    'New Mexico': 'NM', 'Indiana': 'IN', 'Maryland': 'MD', 'Louisiana': 'LA',
    'Idaho': 'ID', 'Wyoming': 'WY', 'Tennessee': 'TN', 'Arizona': 'AZ',
    'Iowa': 'IA', 'Michigan': 'MI', 'Kansas': 'KS', 'Utah': 'UT',
    'Virginia': 'VA', 'Oregon': 'OR', 'Connecticut': 'CT', 'Montana': 'MT',
    'California': 'CA', 'Massachusetts': 'MA', 'West Virginia': 'WV',
    'South Carolina': 'SC', 'New Hampshire': 'NH', 'Wisconsin': 'WI',
    'Vermont': 'VT', 'Georgia': 'GA', 'North Dakota': 'ND',
    'Pennsylvania': 'PA', 'Florida': 'FL', 'Alaska': 'AK', 'Kentucky': 'KY',
    'Hawaii': 'HI', 'Nebraska': 'NE', 'Missouri': 'MO', 'Ohio': 'OH',
    'Alabama': 'AL', 'Rhode Island': 'RI', 'South Dakota': 'SD',
    'Colorado': 'CO', 'New Jersey': 'NJ', 'Washington': 'WA',
    'North Carolina': 'NC', 'New York': 'NY', 'Texas': 'TX',
    'Nevada': 'NV', 'Maine': 'ME'
}

S_AND_P = [
    'Agilent Technologies Inc - A',
    'American Airlines Group - AAL',
    'Advance Auto Parts - AAP',
    'Apple Inc. - AAPL',
    'AbbVie Inc. - ABBV',
    'AmerisourceBergen Corp - ABC',
    'ABIOMED Inc - ABMD',
    'Abbott Laboratories - ABT',
    'Accenture plc - ACN',
    'Adobe Inc. - ADBE',
    'Analog Devices, Inc. - ADI',
    'Archer-Daniels-Midland Co - ADM',
    'Automatic Data Processing - ADP',
    'Autodesk Inc. - ADSK',
    'Ameren Corp - AEE',
    'American Electric Power - AEP',
    'AES Corp - AES',
    'AFLAC Inc - AFL',
    'American International Group - AIG',
    'Assurant - AIZ',
    'Arthur J. Gallagher & Co. - AJG',
    'Akamai Technologies Inc - AKAM',
    'Albemarle Corp - ALB',
    'Align Technology - ALGN',
    'Alaska Air Group Inc - ALK',
    'Allstate Corp - ALL',
    'Allegion - ALLE',
    'Alexion Pharmaceuticals - ALXN',
    'Applied Materials Inc. - AMAT',
    'Amcor plc - AMCR',
    'Advanced Micro Devices Inc - AMD',
    'AMETEK Inc. - AME',
    'Amgen Inc. - AMGN',
    'Ameriprise Financial - AMP',
    'American Tower Corp. - AMT',
    'Amazon.com Inc. - AMZN',
    'Arista Networks - ANET',
    'ANSYS - ANSS',
    'Anthem - ANTM',
    'Aon plc - AON',
    'A.O. Smith Corp - AOS',
    'Apache Corporation - APA',
    'Air Products & Chemicals Inc - APD',
    'Amphenol Corp - APH',
    'Aptiv PLC - APTV',
    'Alexandria Real Estate Equities - ARE',
    'Atmos Energy - ATO',
    'Activision Blizzard - ATVI',
    'AvalonBay Communities - AVB',
    'Broadcom Inc. - AVGO',
    'Avery Dennison Corp - AVY',
    'American Water Works Company Inc - AWK',
    'American Express Co - AXP',
    'AutoZone Inc - AZO',
    'Boeing Company - BA',
    'Bank of America Corp - BAC',
    'Baxter International Inc. - BAX',
    'Best Buy Co. Inc. - BBY',
    'Becton Dickinson - BDX',
    'Franklin Resources - BEN',
    'Brown-Forman Corp. - BF.B',
    'Biogen Inc. - BIIB',
    'Bio-Rad Laboratories - BIO',
    'The Bank of New York Mellon - BK',
    'Booking Holdings Inc - BKNG',
    'Baker Hughes Co - BKR',
    'BlackRock - BLK',
    'Ball Corp - BLL',
    'Bristol-Myers Squibb - BMY',
    'Broadridge Financial Solutions - BR',
    'Berkshire Hathaway - BRK.B',
    'Boston Scientific - BSX',
    'BorgWarner - BWA',
    'Boston Properties - BXP',
    'Citigroup Inc. - C',
    'Conagra Brands - CAG',
    'Cardinal Health Inc. - CAH',
    'Carrier Global - CARR',
    'Caterpillar Inc. - CAT',
    'Chubb Limited - CB',
    'Cboe Global Markets - CBOE',
    'CBRE Group - CBRE',
    'Crown Castle International Corp. - CCI',
    'Carnival Corp. - CCL',
    'Cadence Design Systems - CDNS',
    'CDW - CDW',
    'Celanese - CE',
    'Cerner - CERN',
    'CF Industries Holdings Inc - CF',
    'Citizens Financial Group - CFG',
    'Church & Dwight - CHD',
    'C. H. Robinson Worldwide - CHRW',
    'Charter Communications - CHTR',
    'CIGNA Corp. - CI',
    'Cincinnati Financial - CINF',
    'Colgate-Palmolive - CL',
    'The Clorox Company - CLX',
    'Comerica Inc. - CMA',
    'Comcast Corp. - CMCSA',
    'CME Group Inc. - CME',
    'Chipotle Mexican Grill - CMG',
    'Cummins Inc. - CMI',
    'CMS Energy - CMS',
    'Centene Corporation - CNC',
    'CenterPoint Energy - CNP',
    'Capital One Financial - COF',
    'Cabot Oil & Gas - COG',
    'The Cooper Companies - COO',
    'ConocoPhillips - COP',
    'Costco Wholesale Corp. - COST',
    'Campbell Soup - CPB',
    'Copart Inc - CPRT',
    'Salesforce.com - CRM',
    'Cisco Systems - CSCO',
    'CSX Corp. - CSX',
    'Cintas Corporation - CTAS',
    'Catalent - CTLT',
    'Cognizant Technology Solutions - CTSH',
    'Corteva - CTVA',
    'Citrix Systems - CTXS',
    'CVS Health - CVS',
    'Chevron Corp. - CVX',
    'Concho Resources - CXO',
    'Dominion Energy - D',
    'Delta Air Lines Inc. - DAL',
    'DuPont de Nemours Inc - DD',
    'Deere & Co. - DE',
    'Discover Financial Services - DFS',
    'Dollar General - DG',
    'Quest Diagnostics - DGX',
    'D. R. Horton - DHI',
    'Danaher Corp. - DHR',
    'The Walt Disney Company - DIS',
    'Discovery, Inc. (Class A) - DISCA',
    'Discovery, Inc. (Class C) - DISCK',
    'Dish Network - DISH',
    'Digital Realty Trust Inc - DLR',
    'Dollar Tree - DLTR',
    'Dover Corporation - DOV',
    'Dow Inc. - DOW',
    "Domino's Pizza - DPZ",
    'Duke Realty Corp - DRE',
    'Darden Restaurants - DRI',
    'DTE Energy Co. - DTE',
    'Duke Energy - DUK',
    'DaVita Inc. - DVA',
    'Devon Energy - DVN',
    'DXC Technology - DXC',
    'DexCom - DXCM',
    'Electronic Arts - EA',
    'eBay Inc. - EBAY',
    'Ecolab Inc. - ECL',
    'Consolidated Edison - ED',
    'Equifax Inc. - EFX',
    "Edison Int'l - EIX",
    'Estée Lauder Companies - EL',
    'Eastman Chemical - EMN',
    'Emerson Electric Company - EMR',
    'EOG Resources - EOG',
    'Equinix - EQIX',
    'Equity Residential - EQR',
    'Eversource Energy - ES',
    'Essex Property Trust, Inc. - ESS',
    'Eaton Corporation - ETN',
    'Entergy Corp. - ETR',
    'Etsy - ETSY',
    'Evergy - EVRG',
    'Edwards Lifesciences - EW',
    'Exelon Corp. - EXC',
    'Expeditors - EXPD',
    'Expedia Group - EXPE',
    'Extra Space Storage - EXR',
    'Ford Motor Company - F',
    'Diamondback Energy - FANG',
    'Fastenal Co - FAST',
    'Facebook, Inc. - FB',
    'Fortune Brands Home & Security - FBHS',
    'Freeport-McMoRan Inc. - FCX',
    'FedEx Corporation - FDX',
    'FirstEnergy Corp - FE',
    'F5 Networks - FFIV',
    'Fidelity National Information Services - FIS',
    'Fiserv Inc - FISV',
    'Fifth Third Bancorp - FITB',
    'FLIR Systems - FLIR',
    'Flowserve Corporation - FLS',
    'FleetCor Technologies Inc - FLT',
    'FMC Corporation - FMC',
    'Fox Corporation (Class B) - FOX',
    'Fox Corporation (Class A) - FOXA',
    'First Republic Bank - FRC',
    'Federal Realty Investment Trust - FRT',
    'TechnipFMC - FTI',
    'Fortinet - FTNT',
    'Fortive Corp - FTV',
    'General Dynamics - GD',
    'General Electric - GE',
    'Gilead Sciences - GILD',
    'General Mills - GIS',
    'Globe Life Inc. - GL',
    'Corning Inc. - GLW',
    'General Motors - GM',
    'Alphabet Inc. (Class C) - GOOG',
    'Alphabet Inc. (Class A) - GOOGL',
    'Genuine Parts - GPC',
    'Global Payments Inc. - GPN',
    'Gap Inc. - GPS',
    'Garmin Ltd. - GRMN',
    'Goldman Sachs Group - GS',
    'Grainger (W.W.) Inc. - GWW',
    'Halliburton Co. - HAL',
    'Hasbro Inc. - HAS',
    'Huntington Bancshares - HBAN',
    'Hanesbrands Inc - HBI',
    'HCA Healthcare - HCA',
    'Home Depot - HD',
    'Hess Corporation - HES',
    'HollyFrontier Corp - HFC',
    'Hartford Financial Svc.Gp. - HIG',
    'Huntington Ingalls Industries - HII',
    'Hilton Worldwide Holdings Inc - HLT',
    'Hologic - HOLX',
    "Honeywell Int'l Inc. - HON",
    'Hewlett Packard Enterprise - HPE',
    'HP Inc. - HPQ',
    'Hormel Foods Corp. - HRL',
    'Henry Schein - HSIC',
    'Host Hotels & Resorts - HST',
    'The Hershey Company - HSY',
    'Humana Inc. - HUM',
    'Howmet Aerospace - HWM',
    'International Business Machines - IBM',
    'Intercontinental Exchange - ICE',
    'IDEXX Laboratories - IDXX',
    'IDEX Corporation - IEX',
    'International Flavors & Fragrances - IFF',
    'Illumina Inc - ILMN',
    'Incyte - INCY',
    'IHS Markit Ltd. - INFO',
    'Intel Corp. - INTC',
    'Intuit Inc. - INTU',
    'International Paper - IP',
    'Interpublic Group - IPG',
    'IPG Photonics Corp. - IPGP',
    'IQVIA Holdings Inc. - IQV',
    'Ingersoll Rand - IR',
    'Iron Mountain Incorporated - IRM',
    'Intuitive Surgical Inc. - ISRG',
    'Gartner Inc - IT',
    'Illinois Tool Works - ITW',
    'Invesco Ltd. - IVZ',
    'Jacobs Engineering Group - J',
    'J. B. Hunt Transport Services - JBHT',
    'Johnson Controls International - JCI',
    'Jack Henry & Associates - JKHY',
    'Johnson & Johnson - JNJ',
    'Juniper Networks - JNPR',
    'JPMorgan Chase & Co. - JPM',
    'Kellogg Co. - K',
    'KeyCorp - KEY',
    'Keysight Technologies - KEYS',
    'Kraft Heinz Co - KHC',
    'Kimco Realty - KIM',
    'KLA Corporation - KLAC',
    'Kimberly-Clark - KMB',
    'Kinder Morgan - KMI',
    'Carmax Inc - KMX',
    'Coca-Cola Company - KO',
    'Kroger Co. - KR',
    'Kansas City Southern - KSU',
    'Loews Corp. - L',
    'L Brands Inc. - LB',
    'Leidos Holdings - LDOS',
    'Leggett & Platt - LEG',
    'Lennar Corp. - LEN',
    'Laboratory Corp. of America Holding - LH',
    'L3Harris Technologies - LHX',
    'Linde plc - LIN',
    'LKQ Corporation - LKQ',
    'Lilly (Eli) & Co. - LLY',
    'Lockheed Martin Corp. - LMT',
    'Lincoln National - LNC',
    'Alliant Energy Corp - LNT',
    "Lowe's Cos. - LOW",
    'Lam Research - LRCX',
    'Lumen Technologies - LUMN',
    'Southwest Airlines - LUV',
    'Las Vegas Sands - LVS',
    'Lamb Weston Holdings Inc - LW',
    'LyondellBasell - LYB',
    'Live Nation Entertainment - LYV',
    'Mastercard Inc. - MA',
    'Mid-America Apartments - MAA',
    "Marriott Int'l. - MAR",
    'Masco Corp. - MAS',
    "McDonald's Corp. - MCD",
    'Microchip Technology - MCHP',
    'McKesson Corp. - MCK',
    "Moody's Corp - MCO",
    'Mondelez International - MDLZ',
    'Medtronic plc - MDT',
    'MetLife Inc. - MET',
    'MGM Resorts International - MGM',
    'Mohawk Industries - MHK',
    'McCormick & Co. - MKC',
    'MarketAxess - MKTX',
    'Martin Marietta Materials - MLM',
    'Marsh & McLennan - MMC',
    '3M Company - MMM',
    'Monster Beverage - MNST',
    'Altria Group Inc - MO',
    'The Mosaic Company - MOS',
    'Marathon Petroleum - MPC',
    'Merck & Co. - MRK',
    'Marathon Oil Corp. - MRO',
    'Morgan Stanley - MS',
    'MSCI Inc - MSCI',
    'Microsoft Corp. - MSFT',
    'Motorola Solutions Inc. - MSI',
    'M&T Bank Corp. - MTB',
    'Mettler Toledo - MTD',
    'Micron Technology - MU',
    'Maxim Integrated Products Inc - MXIM',
    'Norwegian Cruise Line Holdings - NCLH',
    'Nasdaq, Inc. - NDAQ',
    'NextEra Energy - NEE',
    'Newmont Corporation - NEM',
    'Netflix Inc. - NFLX',
    'NiSource Inc. - NI',
    'Nike, Inc. - NKE',
    'NortonLifeLock - NLOK',
    'Nielsen Holdings - NLSN',
    'Northrop Grumman - NOC',
    'National Oilwell Varco Inc. - NOV',
    'ServiceNow - NOW',
    'NRG Energy - NRG',
    'Norfolk Southern Corp. - NSC',
    'NetApp - NTAP',
    'Northern Trust Corp. - NTRS',
    'Nucor Corp. - NUE',
    'Nvidia Corporation - NVDA',
    'NVR, Inc. - NVR',
    'Newell Brands - NWL',
    'News Corp. Class B - NWS',
    'News Corp. Class A - NWSA',
    'Realty Income Corporation - O',
    'Old Dominion Freight Line - ODFL',
    'ONEOK - OKE',
    'Omnicom Group - OMC',
    'Oracle Corp. - ORCL',
    "O'Reilly Automotive - ORLY",
    'Otis Worldwide - OTIS',
    'Occidental Petroleum - OXY',
    'Paycom - PAYC',
    'Paychex Inc. - PAYX',
    "People's United Financial - PBCT",
    'PACCAR Inc. - PCAR',
    'Healthpeak Properties - PEAK',
    'Public Service Enterprise Group (PSEG) - PEG',
    'PepsiCo Inc. - PEP',
    'Pfizer Inc. - PFE',
    'Principal Financial Group - PFG',
    'Procter & Gamble - PG',
    'Progressive Corp. - PGR',
    'Parker-Hannifin - PH',
    'PulteGroup - PHM',
    'Packaging Corporation of America - PKG',
    'PerkinElmer - PKI',
    'Prologis - PLD',
    'Philip Morris International - PM',
    'PNC Financial Services - PNC',
    'Pentair plc - PNR',
    'Pinnacle West Capital - PNW',
    'Pool Corporation - POOL',
    'PPG Industries - PPG',
    'PPL Corp. - PPL',
    'Perrigo - PRGO',
    'Prudential Financial - PRU',
    'Public Storage - PSA',
    'Phillips 66 - PSX',
    'PVH Corp. - PVH',
    'Quanta Services Inc. - PWR',
    'Pioneer Natural Resources - PXD',
    'PayPal - PYPL',
    'QUALCOMM Inc. - QCOM',
    'Qorvo - QRVO',
    'Royal Caribbean Group - RCL',
    'Everest Re Group Ltd. - RE',
    'Regency Centers Corporation - REG',
    'Regeneron Pharmaceuticals - REGN',
    'Regions Financial Corp. - RF',
    'Robert Half International - RHI',
    'Raymond James Financial Inc. - RJF',
    'Ralph Lauren Corporation - RL',
    'ResMed - RMD',
    'Rockwell Automation Inc. - ROK',
    'Rollins Inc. - ROL',
    'Roper Technologies - ROP',
    'Ross Stores - ROST',
    'Republic Services Inc - RSG',
    'Raytheon Technologies - RTX',
    'SBA Communications - SBAC',
    'Starbucks Corp. - SBUX',
    'Charles Schwab Corporation - SCHW',
    'Sealed Air - SEE',
    'Sherwin-Williams - SHW',
    'SVB Financial - SIVB',
    'JM Smucker - SJM',
    'Schlumberger Ltd. - SLB',
    'SL Green Realty - SLG',
    'Snap-on - SNA',
    'Synopsys Inc. - SNPS',
    'Southern Company - SO',
    'Simon Property Group Inc - SPG',
    'S&P Global, Inc. - SPGI',
    'Sempra Energy - SRE',
    'STERIS plc - STE',
    'State Street Corp. - STT',
    'Seagate Technology - STX',
    'Constellation Brands - STZ',
    'Stanley Black & Decker - SWK',
    'Skyworks Solutions - SWKS',
    'Synchrony Financial - SYF',
    'Stryker Corp. - SYK',
    'Sysco Corp. - SYY',
    'AT&T Inc. - T',
    'Molson Coors Beverage Company - TAP',
    'TransDigm Group - TDG',
    'Teledyne Technologies - TDY',
    'TE Connectivity Ltd. - TEL',
    'Teradyne - TER',
    'Truist Financial - TFC',
    'Teleflex - TFX',
    'Target Corp. - TGT',
    'Tiffany & Co. - TIF',
    'TJX Companies Inc. - TJX',
    'Thermo Fisher Scientific - TMO',
    'T-Mobile US - TMUS',
    'Tapestry, Inc. - TPR',
    'T. Rowe Price Group - TROW',
    'The Travelers Companies Inc. - TRV',
    'Tractor Supply Company - TSCO',
    'Tesla, Inc. - TSLA',
    'Tyson Foods - TSN',
    'Trane Technologies plc - TT',
    'Take-Two Interactive - TTWO',
    'Twitter, Inc. - TWTR',
    'Texas Instruments - TXN',
    'Textron Inc. - TXT',
    'Tyler Technologies - TYL',
    'Under Armour (Class C) - UA',
    'Under Armour (Class A) - UAA',
    'United Airlines Holdings - UAL',
    'UDR, Inc. - UDR',
    'Universal Health Services - UHS',
    'Ulta Beauty - ULTA',
    'UnitedHealth Group Inc. - UNH',
    'Unum Group - UNM',
    'Union Pacific Corp - UNP',
    'United Parcel Service - UPS',
    'United Rentals, Inc. - URI',
    'U.S. Bancorp - USB',
    'Visa Inc. - V',
    'Varian Medical Systems - VAR',
    'VF Corporation - VFC',
    'ViacomCBS - VIAC',
    'Valero Energy - VLO',
    'Vulcan Materials - VMC',
    'Vornado Realty Trust - VNO',
    'Vontier - VNT',
    'Verisk Analytics - VRSK',
    'Verisign Inc. - VRSN',
    'Vertex Pharmaceuticals Inc - VRTX',
    'Ventas Inc - VTR',
    'Viatris - VTRS',
    'Verizon Communications - VZ',
    'Westinghouse Air Brake Technologies Corp - WAB',
    'Waters Corporation - WAT',
    'Walgreens Boots Alliance - WBA',
    'Western Digital - WDC',
    'WEC Energy Group - WEC',
    'Welltower Inc. - WELL',
    'Wells Fargo - WFC',
    'Whirlpool Corp. - WHR',
    'Willis Towers Watson - WLTW',
    'Waste Management Inc. - WM',
    'Williams Companies - WMB',
    'Walmart - WMT',
    'W. R. Berkley Corporation - WRB',
    'WestRock - WRK',
    'West Pharmaceutical Services - WST',
    'Western Union Co - WU',
    'Weyerhaeuser - WY',
    'Wynn Resorts Ltd - WYNN',
    'Xcel Energy Inc - XEL',
    'Xilinx - XLNX',
    'Exxon Mobil Corp. - XOM',
    'Dentsply Sirona - XRAY',
    'Xerox - XRX',
    'Xylem Inc. - XYL',
    'Yum! Brands Inc - YUM',
    'Zimmer Biomet - ZBH',
    'Zebra Technologies - ZBRA',
    'Zions Bancorp - ZION',
    'Zoetis - ZTS',
    'Other',
    '--- Select a Company ---'
]
